# Generated by Django 4.2.5 on 2023-09-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fahrenheit', models.FloatField(default=45)),
            ],
        ),
    ]
