# Generated by Django 4.2.5 on 2023-11-06 16:56

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_platform', '0002_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name=django.contrib.auth.models.User)),
                ('location', models.CharField(blank=True, max_length=250, verbose_name=django.contrib.auth.models.User)),
            ],
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
